---
- name: run nextcloud container
  docker_container:
    name: nextcloud-rvgate-nl
    image: nextcloud
    pull: yes
    state: started
    privileged: yes
    volumes:
      - nextcloud-data:/var/www/html/data/
    env:
      VIRTUAL_HOST: "nextcloud.rvgate.nl"
