---
- name: run nextcloud container
  docker_container:
    name: cloud-rvgate-nl
    image: nextcloud
    pull: yes
    state: started
    privileged: yes
    volumes:
      - nextcloud-data:/var/www/html/data/
    env:
      VIRTUAL_HOST: "cloud.rvgate.nl"
