---
- name: run pritunl container
  docker_container:
    name: pritunl-vpn
    image: jippi/pritunl
    pull: yes
    state: started
    privileged: yes
    ports:
      - 1194:1194/tcp
      - 1194:1194/udp
      - 21:1194/tcp
      - 21:1194/udp
    volumes:
      - vpn_mongodb:/var/lib/mongodb
      - vpn_pritunl:/var/lib/pritunl
      - vpn_config:/etc
    env:
      VIRTUAL_HOST: vpn.rvgate.nl
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https