---
- name: install docker
  dnf:
    name: docker

- name: pip packages
  pip:
    name: docker

- name: run watchtower container
  docker_container:
    name: watchtower-autoupdate
    image: v2tec/watchtower
    restart_policy: unless-stopped
    state: stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: run portainer container
  docker_container:
    name: portainer-rvgate-nl
    image: portainer/portainer
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer
    env:
      VIRTUAL_HOST: "portainer.rvgate.nl"
      VIRTUAL_PORT: "9000"
    command: "--admin-password '$2y$05$BJ3MUBMolVeXjt9rnrDJBOqo2/qMtXUMJPCOaUTwTieBIY5v8iYE6'"