---
- name: Set locales
  include_role:
    name: tersmitten.locales
  vars:
    locales_present: en_US.UTF-8
    locales_default:
      lang: en_US.UTF-8
      language: en_US:en
      lc_all: en_US.UTF-8
