---
- name: Packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: True
  with_items:
    - ansible
    - curl
    - dnsutils
    - git
    - htop
    - iftop
    - iotop
    - nload
    - nmap
    - ntp
    - ntpdate
    - openssh-server
    - python
    - screen
    - ssh
    - tig
    - traceroute
    - tree
    - vim
    - whois

- name: Remove unused dependencies (ansible 2.3)
  shell: apt autoremove -y
  changed_when: False
