---
- name: Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - crontabs
    - curl
    - dnf-plugins-core
    - git
    - htop
    - httpd-tools
    - iftop
    - iotop
    - nload
    - nmap
    - python
    - screen
    - telnet
    - tig
    - traceroute
    - tree
    - vim
    - whois
