---
- name: install public keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/rvgate-linux.pub
    - public_keys/rvgate-phone.pub
    - public_keys/rvgate-virtual.pub
    - public_keys/rvgate-windows.pub
