---
- name: Install public keys
  include_role:
    name: tersmitten.ssh-keys
  vars:
    ssh_keys_authorized_keys:
      - owner: root
        src: ssh-keys/rvgate-linux.pub
      - owner: root
        src: ssh-keys/rvgate-windows.pub
      - owner: root
        src: ssh-keys/rvgate-phone.pub
