---
- name: Update Timezone to Etc/UTC
  copy:
    content: "Etc/UTC\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: timezone
  notify: reconfigure-timezone-data
