---
- name: install certbot
  package:
    name: certbot
    state: present

- name: install certbot cloudflare plugin
  pip:
    name: certbot-dns-cloudflare
    state: present

- name: create letsencrypt directory
  file:
    path: /etc/letsencrypt
    state: directory
    mode: 0700

- name: copy cloudflare configuration
  copy:
    src: letsencrypt-cloudflare.ini
    dest: /etc/letsencrypt/cloudflare.ini
    mode: 0400

- name: request first wildcard certificate
  command: /usr/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d rvgate.nl,*.rvgate.nl --preferred-challenges dns-01 --non-interactive --agree-tos -m info@rvgate.nl
  args:
    creates: /etc/letsencrypt/live/rvgate.nl/privkey.pem

- name: symlink certificate to correct name
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - {src: /etc/letsencrypt/live/rvgate.nl/cert.pem, dest: /etc/letsencrypt/live/rvgate.nl/rvgate.nl.crt}
    - {src: /etc/letsencrypt/live/rvgate.nl/privkey.pem, dest: /etc/letsencrypt/live/rvgate.nl/rvgate.nl.key}

- name: setup certbot cronjob
  cron:
    name: certbot
    special_time: weekly
    job: "/usr/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d rvgate.nl,*.rvgate.nl --preferred-challenges dns-01 --non-interactive --agree-tos -m info@rvgate.nl > /dev/null"
    state: present
