---
- name: Install moyenne app
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:

      - listen: "80"
        server_name: "_"
        root: "/var/www/www.rvgate.nl"
        index: "index.html"
        filename: "www.rvgate.nl.80.conf"
        template: "{{ playbook_dir}}/roles/webserver/templates/vhost.j2"
        extra_parameters: |
          location / {
            return 302 https://$host$request_uri;
          }
          location /.well-known/ {
            # do not redirect for lets-encrypt validation
          }

      - listen: "443 ssl http2"
        server_name: "_ rvgate.nl *.rvgate.nl"
        root: "/var/www/www.rvgate.nl"
        index: "index.html"
        filename: "www.rvgate.nl.443.conf"
        template: "{{ playbook_dir}}/roles/webserver/templates/vhost.j2"
        extra_parameters: |
          location /moyenne {
            return 302 https://moyenne.rvgate.nl/;
          }
          location /ynabconverter {
            return 302 https://ynab.rvgate.nl/;
          }
          ssl_certificate     /etc/letsencrypt/live/rvgate.nl/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/rvgate.nl/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "moyenne.rvgate.nl"
        root: "/var/www/moyenne.rvgate.nl"
        index: "index.html"
        filename: "moyenne.rvgate.nl.443.conf"
        template: "{{ playbook_dir}}/roles/webserver/templates/vhost.j2"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
          ssl_certificate     /etc/letsencrypt/live/rvgate.nl/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/rvgate.nl/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "ynab.rvgate.nl"
        root: "/var/www/ynab.rvgate.nl"
        index: "index.html"
        filename: "ynab.rvgate.nl.443.conf"
        template: "{{ playbook_dir}}/roles/webserver/templates/vhost.j2"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
          ssl_certificate     /etc/letsencrypt/live/rvgate.nl/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/rvgate.nl/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "standen.rvgate.nl"
        root: "/var/www/standen.rvgate.nl"
        index: "index.html"
        filename: "standen.rvgate.nl.443.conf"
        template: "{{ playbook_dir}}/roles/webserver/templates/vhost.j2"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
          ssl_certificate     /etc/letsencrypt/live/rvgate.nl/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/rvgate.nl/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

