---
- name: Remove original index file
  file:
    dest: /var/www/html/index.nginx-debian.html
    state: absent

- name: Deploy websites
  git:
    repo: "{{ item.repo }}"
    dest: "/var/www/{{ item.domain }}"
    depth: 1
  with_items:
    - { domain: www.rvgate.nl, repo: "https://github.com/rvgate/rvgate.nl.git" }
    - { domain: moyenne.rvgate.nl, repo: "https://github.com/rvgate/MoyenneBerekening.git" }
    - { domain: ynab.rvgate.nl, repo: "https://github.com/rvgate/YnabConverter.git" }

- name: Link .well-known for certificate renewal
  file:
    src: /var/www/html/.well-known
    dest: "/var/www/{{ item.domain }}/.well-known"
    state: link
    force: True
  with_items:
    - { domain: www.rvgate.nl, repo: "https://github.com/rvgate/rvgate.nl.git" }
    - { domain: moyenne.rvgate.nl, repo: "https://github.com/rvgate/MoyenneBerekening.git" }
    - { domain: ynab.rvgate.nl, repo: "https://github.com/rvgate/YnabConverter.git" }
